/* eslint-disable @typescript-eslint/camelcase */

import { Admin } from "../../types";
import { createAdminEntities } from "./AdminEntityConverter";

test("convert admin entity", () => {
  const admins: Admin[] = [
    {
      id: 6,
      name: "Test Account",
      directory_user: false,
      full_name: "Test Account Full",
      email: "test@test.com",
      email_address: "test@test.com",
      enabled: "Enabled",
      force_password_change: false,
      access_level: "Group Access",
      privilege_set: "Custom",
      groups: {
        group: {
          id: 3,
          name: "Not all groups have members inside in api",
          site: { id: -1, name: "None" },
          privileges: {
            jss_objects: { privilege: "Read eBooks" },
            jss_settings: {},
            recon: {},
            casper_admin: {},
            casper_remote: {},
            casper_imaging: {},
          },
        },
      },
    },
    {
      id: 4,
      name: "jupiterone-dev",
      directory_user: false,
      full_name: "",
      email: "",
      email_address: "",
      password_sha256: "meshayousha",
      enabled: "Enabled",
      force_password_change: false,
      access_level: "Full Access",
      privilege_set: "Auditor",
      privileges: {
        jss_objects: ["Test Privileges"],
        jss_settings: ["Test Privileges"],
        jss_actions: ["Change Password", "View Event Logs"],
        recon: [],
        casper_admin: ["Use Casper Admin"],
        casper_remote: [],
        casper_imaging: [],
      },
    },
    {
      id: 2,
      name: "user.d",
      directory_user: false,
      full_name: "User D",
      email: "user.d@example.com",
      email_address: "user.d@example.com",
      enabled: "Enabled",
      force_password_change: false,
      access_level: "Full Access",
      privilege_set: "Administrator",
      privileges: {
        jss_objects: ["Test Privileges"],
        jss_settings: ["Test Privileges"],
        jss_actions: ["Test Privileges"],
        recon: ["Add Computers Remotely", "Create QuickAdd Packages"],
        casper_admin: ["Use Casper Admin", "Save With Casper Admin"],
        casper_remote: ["Test Privileges"],
        casper_imaging: ["Test Privileges"],
      },
    },
    {
      id: 1,
      name: "user.b",
      directory_user: false,
      full_name: "",
      email: "user.b@example.com",
      email_address: "user.b@example.com",
      enabled: "Enabled",
      force_password_change: false,
      access_level: "Full Access",
      privilege_set: "Administrator",
      privileges: {
        jss_objects: ["Test Privileges"],
        jss_settings: ["Test Privileges"],
        jss_actions: ["Test Privileges"],
        recon: ["Add Computers Remotely", "Create QuickAdd Packages"],
        casper_admin: ["Use Casper Admin", "Save With Casper Admin"],
        casper_remote: ["Test Privileges"],
        casper_imaging: ["Test Privileges"],
      },
    },
    {
      id: 3,
      name: "user.a",
      directory_user: false,
      full_name: "User A",
      email: "user.a@example.com",
      email_address: "user.a@example.com",
      enabled: "Enabled",
      force_password_change: false,
      access_level: "Full Access",
      privilege_set: "Administrator",
      privileges: {
        jss_objects: ["Test Privileges"],
        jss_settings: ["Test Privileges"],
        jss_actions: ["Test Privileges"],
        recon: ["Add Computers Remotely", "Create QuickAdd Packages"],
        casper_admin: ["Use Casper Admin", "Save With Casper Admin"],
        casper_remote: ["Test Privileges"],
        casper_imaging: ["Test Privileges"],
      },
    },
    {
      id: 5,
      name: "jupiterone-underpriv",
      directory_user: false,
      full_name: "JupiterOne",
      email: "",
      email_address: "",
      enabled: "Enabled",
      force_password_change: false,
      access_level: "Full Access",
      privilege_set: "Custom",
      privileges: {
        jss_objects: [],
        jss_settings: [],
        jss_actions: [],
        recon: [],
        casper_admin: [],
        casper_remote: [],
        casper_imaging: [],
      },
    },
  ];

  expect(createAdminEntities(admins)).toEqual([
    {
      _class: "User",
      _key: "jamf_user_6",
      _type: "jamf_user",
      _rawData: [{ name: "default", rawData: admins[0] }],
      accessLevel: "Group Access",
      admin: true,
      directoryUser: false,
      displayName: "Test Account",
      email: "test@test.com",
      emailAddress: "test@test.com",
      enabled: "Enabled",
      forcePasswordChange: false,
      fullName: "Test Account Full",
      name: "Test Account",
      privilegeSet: "Custom",
    },
    {
      _class: "User",
      _key: "jamf_user_4",
      _type: "jamf_user",
      _rawData: [{ name: "default", rawData: admins[1] }],
      accessLevel: "Full Access",
      admin: true,
      directoryUser: false,
      displayName: "jupiterone-dev",
      email: "",
      emailAddress: "",
      enabled: "Enabled",
      forcePasswordChange: false,
      fullName: "",
      name: "jupiterone-dev",
      privilegeSet: "Auditor",
    },
    {
      _class: "User",
      _key: "jamf_user_2",
      _type: "jamf_user",
      _rawData: [{ name: "default", rawData: admins[2] }],
      accessLevel: "Full Access",
      admin: true,
      directoryUser: false,
      displayName: "user.d",
      email: "user.d@example.com",
      emailAddress: "user.d@example.com",
      enabled: "Enabled",
      forcePasswordChange: false,
      fullName: "User D",
      name: "user.d",
      permissions: ["Administrator"],
      privilegeSet: "Administrator",
    },
    {
      _class: "User",
      _key: "jamf_user_1",
      _type: "jamf_user",
      _rawData: [{ name: "default", rawData: admins[3] }],
      accessLevel: "Full Access",
      admin: true,
      directoryUser: false,
      displayName: "user.b",
      email: "user.b@example.com",
      emailAddress: "user.b@example.com",
      enabled: "Enabled",
      forcePasswordChange: false,
      fullName: "",
      name: "user.b",
      permissions: ["Administrator"],
      privilegeSet: "Administrator",
    },
    {
      _class: "User",
      _key: "jamf_user_3",
      _type: "jamf_user",
      _rawData: [{ name: "default", rawData: admins[4] }],
      accessLevel: "Full Access",
      admin: true,
      directoryUser: false,
      displayName: "user.a",
      email: "user.a@example.com",
      emailAddress: "user.a@example.com",
      enabled: "Enabled",
      forcePasswordChange: false,
      fullName: "User A",
      name: "user.a",
      permissions: ["Administrator"],
      privilegeSet: "Administrator",
    },
    {
      _class: "User",
      _key: "jamf_user_5",
      _type: "jamf_user",
      _rawData: [{ name: "default", rawData: admins[5] }],
      accessLevel: "Full Access",
      admin: true,
      directoryUser: false,
      displayName: "jupiterone-underpriv",
      email: "",
      emailAddress: "",
      enabled: "Enabled",
      forcePasswordChange: false,
      fullName: "JupiterOne",
      name: "jupiterone-underpriv",
      privilegeSet: "Custom",
    },
  ]);
});
