import { Computer } from "../../types";
import { createComputerEntities } from "./ComputerEntityConverter";

test("convert computer entity", () => {
  const computers: Computer[] = [
    {
      id: 1,
      name: "PlayerOne’s MacBook",
      managed: true,
      username: "player.one",
      model: "MacBookPro13,3",
      department: "",
      building: "",
      mac_address: "AA:BB:CC:11:22:33",
      udid: "8195CA16-7FFE-5855-A3DD-53FD768FA558",
      serial_number: "SERIAL123",
      report_date_utc: "2019-05-06T13:33:08.196+0000",
      report_date_epoch: 1557149588196,
    },
    {
      id: 2,
      name: "PlayerOne’s MacBook",
      managed: true,
      username: "player.one",
      model: "MacBookPro13,3",
      department: "",
      building: "",
      mac_address: "78:4F:43:7F:7D:CB",
      udid: "8195CA16-7FFE-5855-A3DD-53FD76ABC123",
      serial_number: "5EGTF1C02T70",
      report_date_utc: "2019-05-06T13:33:08.196+0000",
      report_date_epoch: 1557149588196,
    },
  ];

  const computerDetails: any[] = [
    {
      general: {
        id: 1,
        name: "Jhon’s AcmaCorp MacBook",
        mac_address: "11:22:33:44:55:66",
        alt_mac_address: "11:22:33:44:55:66",
        ip_address: "11.22.33.4",
        last_reported_ip: "111.22.333.444",
        serial_number: "123T123ESTT1",
        udid: "1234TE12-3STT-1234-E1ST-23TE412ST341",
        jamf_version: "10.12.0-t1555503901",
        platform: "Mac",
        barcode_1: "",
        barcode_2: "",
        asset_tag: "",
        remote_management: {
          managed: true,
          management_username: "macOS",
          management_password_sha256:
            "12341te2st3t412341e23stt41e2s341tt23est4tes12t34123te4st1t0e1234",
        },
        mdm_capable: true,
        mdm_capable_users: {
          mdm_capable_user: "jhon.doe",
        },
        management_status: {
          enrolled_via_dep: false,
          user_approved_enrollment: true,
          user_approved_mdm: true,
        },
        report_date: "2019-05-20 14:53:27",
        report_date_epoch: 1558364007680,
        report_date_utc: "2019-05-20T14:53:27.680+0000",
        last_contact_time: "2019-05-23 11:25:05",
        last_contact_time_epoch: 1558610705298,
        last_contact_time_utc: "2019-05-23T11:25:05.298+0000",
        initial_entry_date: "2019-04-22",
        initial_entry_date_epoch: 1555937998405,
        initial_entry_date_utc: "2019-04-22T12:59:58.405+0000",
        last_cloud_backup_date_epoch: 0,
        last_cloud_backup_date_utc: "",
        last_enrolled_date_epoch: 1555938179240,
        last_enrolled_date_utc: "2019-04-22T13:02:59.240+0000",
        distribution_point: "",
        sus: "",
        netboot_server: "",
        site: {
          id: 1,
          name: "Test site",
        },
        itunes_store_account_is_active: true,
      },
      location: {
        username: "jhon.doe",
        realname: "Jhon Doe",
        real_name: "Jhon Doe",
        email_address: "jhon.doe@acmacorp.com",
        position: "CISO",
        phone: "1111111111",
        phone_number: "1111111111",
        department: "",
        building: "",
        room: "",
      },
      purchasing: {
        is_purchased: true,
        is_leased: false,
        po_number: "",
        vendor: "",
        applecare_id: "",
        purchase_price: "",
        purchasing_account: "",
        po_date: "",
        po_date_epoch: 0,
        po_date_utc: "",
        warranty_expires: "",
        warranty_expires_epoch: 0,
        warranty_expires_utc: "",
        lease_expires: "",
        lease_expires_epoch: 0,
        lease_expires_utc: "",
        life_expectancy: 0,
        purchasing_contact: "",
        os_applecare_id: "",
        os_maintenance_expires: "",
        attachments: [],
      },
      peripherals: [],
      hardware: {
        make: "Apple",
        model: "15-inch Retina MacBook Pro with TouchID (Late 2016)",
        model_identifier: "MacBookPro13,3",
        os_name: "Mac OS X",
        os_version: "10.13.6",
        os_build: "17G6030",
        master_password_set: false,
        active_directory_status: "Not Bound",
        service_pack: "",
        processor_type: "Intel Core i7",
        processor_architecture: "x86_64",
        processor_speed: 2900,
        processor_speed_mhz: 2900,
        number_processors: 1,
        number_cores: 4,
        total_ram: 16384,
        total_ram_mb: 16384,
        boot_rom: "254.0.0.0.0",
        bus_speed: 0,
        bus_speed_mhz: 0,
        battery_capacity: 83,
        cache_size: 8192,
        cache_size_kb: 8192,
        available_ram_slots: 0,
        optical_drive: "",
        nic_speed: "n/a",
        smc_version: "2.38f7",
        ble_capable: true,
        sip_status: "Enabled",
        gatekeeper_status: "App Store and identified developers",
        xprotect_version: "2103",
        institutional_recovery_key: "Not Present",
        disk_encryption_configuration: "",
        filevault2_users: ["jhon.doe"],
        storage: [
          {
            disk: "disk0",
            model: "APPLE SSD SM1024L",
            revision: "CXS6AA0Q",
            serial_number: "C02706400ADGVFW1H",
            size: 1048576,
            drive_capacity_mb: 1048576,
            connection_type: "NO",
            smart_status: "",
            partition: {
              name: "Macintosh HD (Boot Partition)",
              size: 953904,
              type: "boot",
              partition_capacity_mb: 953904,
              percentage_full: 66,
              filevault_status: "Encrypted",
              filevault_percent: 100,
              filevault2_status: "Encrypted",
              filevault2_percent: 100,
              boot_drive_available_mb: 356516,
              lvgUUID: "",
              lvUUID: "",
              pvUUID: "",
            },
          },
          {
            disk: "disk1",
            model: "APPLE SSD SM1024L",
            revision: "CXS6AA0Q",
            serial_number: "C02706400ADGVFW1H",
            size: 1048576,
            drive_capacity_mb: 1048576,
            connection_type: "NO",
            smart_status: "",
          },
        ],
        mapped_printers: [
          {
            name: "Test",
            uri: "dnssd://Test._pdl-datastream._tcp.local./?bidi",
            type: "Test type",
            location: "",
          },
        ],
      },
      certificates: [
        {
          common_name: "test",
          identity: false,
          expires_utc: "2017-06-22T11:55:56.000+0000",
          expires_epoch: 1498132556000,
          name: "jhon.doe",
        },
      ],
      software: {
        unix_executables: [],
        licensed_software: [],
        installed_by_casper: [],
        installed_by_installer_swu: ["Test"],
        applications: [
          {
            name: "Test.app",
            path: "/Applications/Test.app",
            version: "7.0.0.485",
          },
        ],
        fonts: [],
        plugins: [],
      },
      extension_attributes: [],
      groups_accounts: {
        computer_group_memberships: ["All Managed Clients"],
        local_accounts: [
          {
            name: "jhon.doe",
            realname: "Jhon Doe",
            uid: "501",
            home: "/Users/jhon",
            home_size: "-1MB",
            home_size_mb: -1,
            administrator: true,
            filevault_enabled: true,
          },
          {
            name: "macOS",
            realname: "macOS",
            uid: "502",
            home: "/Users/macOS",
            home_size: "-1MB",
            home_size_mb: -1,
            administrator: true,
            filevault_enabled: false,
          },
        ],
        user_inventories: {
          disable_automatic_login: true,
          user: {
            username: "macOS",
            password_history_depth: "",
            password_min_length: "",
            password_max_age: "",
            password_min_complex_characters: "",
            password_require_alphanumeric: "false",
          },
        },
      },
      iphones: [],
      configuration_profiles: [
        {
          id: 1,
          name: "TestName",
          uuid: "test_uuid",
          is_removable: false,
        },
      ],
    },
  ];

  const entities = createComputerEntities(computers, computerDetails);

  expect(entities).toEqual([
    {
      _class: ["Host", "Device"],
      _key: "user_endpoint_1",
      _type: "user_endpoint",
      building: "",
      department: "",
      disks:
        '[{"disk":"disk0","partitionName":"Macintosh HD (Boot Partition)"},{"disk":"disk1"}]',
      displayName: "PlayerOne’s MacBook",
      encrypted: true,
      id: 1,
      macAddress: "AA:BB:CC:11:22:33",
      managed: true,
      model: "MacBookPro13,3",
      name: "PlayerOne’s MacBook",
      reportDateEpoch: 1557149588196,
      reportDateUtc: "2019-05-06T13:33:08.196+0000",
      serialNumber: "SERIAL123",
      udid: "8195CA16-7FFE-5855-A3DD-53FD768FA558",
      username: "player.one",
    },
    {
      _class: ["Host", "Device"],
      _key: "user_endpoint_2",
      _type: "user_endpoint",
      building: "",
      department: "",
      displayName: "PlayerOne’s MacBook",
      id: 2,
      macAddress: "78:4F:43:7F:7D:CB",
      managed: true,
      model: "MacBookPro13,3",
      name: "PlayerOne’s MacBook",
      reportDateEpoch: 1557149588196,
      reportDateUtc: "2019-05-06T13:33:08.196+0000",
      serialNumber: "5EGTF1C02T70",
      udid: "8195CA16-7FFE-5855-A3DD-53FD76ABC123",
      username: "player.one",
      disks: "",
      encrypted: false,
    },
  ]);
});
