openapi: 3.0.1
info:
  title: '@jupiterone/graph-jamf'
  description: A JupiterOne Integration for https://jamf.com
  x-cortex-git:
    github:
      repository: JupiterOne/graph-jamf
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-jamf'
